### PR TITLE
Change ligo from next to stable version

### PR DESCRIPTION
**Pull request by jchenche**
### ✅ Required for Merging

- [x] 🏄‍♂️ Myself and others have built this branch and done manual testing on the change
- [x] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [x] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] ⛵ Documentation is added/updated for the release version 
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🖥 Required changes to the VScE have been made
- [ ] 👷 Required updates to scaffolds have been made

### 🙅 Not-Required

- [ ] 🛑 (drag items from above to this list to remove from requirements)

----------------------------------------------------------------------------------------------------------------------------

## 🪁 Description

Made a change in the LIGO plugin to point to the most recent stable version of LIGO docker image (but not using the `latest` nor `stable` tag).

## 🎢 Test Plan

Please describe the testing strategy and plan for this PR

----------------------------------------------------------------------------------------------------------------------------

### 🛸 Type of Change

- [ ] 🧹 Chore ➾
- [x] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [x] 🏗️ Refactor ➾
- [ ] 🚀 Release ➾

----------------------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by hu3man — APPROVED** [review]

**Review by mweichert — CHANGES_REQUESTED** [review]
I would suggest that we use a specific tag rather than a generic label like 'stable'. Reason being, is that docker doesn't track internally what version of 'stable' you might already have installed.  This puts more onus on us to keep our versions up-to-date, but kind of dove-tails into @jevonearth's suggestions in standup today about monitoring ligo updates.

**Comment by jchenche** [comment]
> I would suggest that we use a specific tag rather than a generic label like 'stable'. Reason being, is that docker doesn't track internally what version of 'stable' you might already have installed. This puts more onus on us to keep our versions up-to-date, but kind of dove-tails into @jevonearth's suggestions in standup today about monitoring ligo updates.

@mweichert When you say "tag", are you referring to the docker image tag or the LIGO version?

**Comment by hu3man** [comment]
MVP for this ticket:

- Hardcode the version to the current latest version (NOT next, stable, etc)
- Add a step to the release process to update this

**Review by AlirezaHaghshenas — APPROVED** [review]
I love the spirit of Boy Scot Rule: you clean-up a bit whenever you touch a piece of code.

**Review by mweichert — APPROVED** [review]

**Pull request merged**
