### PR TITLE
update taquito plugin e2e tests

### PR DESCRIPTION
**Pull request by michaelkernaghan**
# 🌮 Taqueria PR

## 🪁 Description
Close#1606
Convert the e2e tests for Taquito plugin to use a safe testing library and make tests atomic.
Various bits of polish and presentation improvements 
Setup for local loading of plugins by relative path traversal

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

_Please include a summary of the changes to the codebase._ _Please also include relevant motivation and context for the change_
_(e.g. what was the existing behaviour, why did it break, etc.)_

## 🎢 Test Plan

_Please describe the testing strategy and plan for this PR. Keep this lightweight and anticipate any testing challenges_

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [ ] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

### CODE REVIEW

**Review by jchenche — APPROVED** [review]

**Review by mweichert — DISMISSED** [review]
Hey @michaelkernaghan 

I do like the readability of these tests. Good stuff!

One thing we discussed offline is that the sequence of steps in a test case can throw an exception which means that the cleanup function won't get called. That could cause problems with test cases that run later downstream.

I think what would be best is to use the afterAll hook for proper teardown, as they're guaranteed to run regardless of whether the code of a test case throws.

E.g.:
```ts
const { execute, spawn, cleanup } = await prepareEnvironment(); // should this go in beforeAll instead? Not sure

describe('E2E Testing for taqueria taquito plugin', ()=>{
    // Work that is global to all tests in the describe block go here
    const taqueriaProjectPath = 'scrap/auto-test-taquito-plugin';
    const contractRegex = new RegExp(/(KT1)+\w{33}?/);
    afterAll(cleanup);

    test('Verify that the taquito plugin exposes the associated commands in the help menu', () => {
      expect.assertions(1)
      const { waitForText } = await spawn('taq', 'init test-project');
      await waitForText("Project taq'ified!");
      const { stdout } = await execute('taq', '--help --projectDir=./test-project', './test-project');
      expect(stdout).toContain('taq [command]');
    });
}
```
This approach has the following advantages:
- Each test is started with a clean environment
- cleanup() is guaranteed to be called even when an await call throws
- if an await call throws before we make an assertion, we'll know that by utilizing `expect.assertions(1)`

Thanks, Mike.

**Comment by michaelkernaghan** [comment]
> ```ts
>    const { execute, spawn, cleanup } = await prepareEnvironment(); // should this go in beforeAll instead? Not sure
>     afterAll(cleanup);
> ```

Yes, I plan to do these refactorings after having worked through the essential elements and made sure they work. Thanks.

**Review by egarson — APPROVED** [review]
Let's move forward with other priorities.
This is more than good enough for now.

**Review by egarson — APPROVED** [review]
LGTM

**Pull request merged**
