### PR TITLE
updated ligo plugin E2E tests

### PR DESCRIPTION
**Pull request by michaelkernaghan**
# 🌮 Taqueria PR

## 🪁 Description

Revised the E2E tests to be better contained and self-explanatory

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

update the e2e test file taqueria-ligo-plugin,spec.ts

## 🎢 Test Plan

Tests will run and pass in CICD

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [ ] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

### CODE REVIEW

**Review by jchenche — APPROVED** [review]

**Review by mweichert — CHANGES_REQUESTED** [review]
Hey Michael. See comments here:
https://github.com/ecadlabs/taqueria/pull/1631#pullrequestreview-1219701272

**Comment by michaelkernaghan** [comment]
Yes, I plan to do these refactorings after having worked through the essential elements and made sure they work. Thanks. Please note it is not going to work as you describe here since Jest doesn't support returning a promise from the describe callback. We can have asynchronous tests, but the test suite (the describe block) needs to be synchronous. The helper functions have to go in 'before all' blocks and 'after all,' which can be async. As well we are interested in tests failing fast. If there is a test fail, we don't really care about cleanup, as a failure must be fixed. You can satisfy yourself that given two tests, one of which will fail and skip the cleanup, the following test will not be affected because the setup for that next test will run a cleanup. The whole point of the library is to create completely isolated instances to run the cli in and destroy them afterwards. The current E2E setup does a lot of gymnastics to try to do this but misses memory leaks etc. Using this library will mean giving up some of the encapsulation and use of helper functions devs may be used to, but for test code; it is essential to avoid any hidden or hard to find code that may be affecting the test behaviour. For all its good points, the one big problem with current E2E tests is mysterious sub-functions and helper code.

**Comment by michaelkernaghan** [comment]
As described, the requested changes are either unnecessary or misdescribe the adopted library.

**Review by egarson — APPROVED** [review]
LGTM

**Pull request merged**
