### PR TITLE
add archetype plugin in ts

### PR DESCRIPTION
**Pull request by guillaumeduhamel**

### CODE REVIEW

**Comment by guillaumeduhamel** [comment]
@GImbrailo done, let me know if you need further actions

**Comment by mweichert** [comment]
@guillaumeduhamel we just need you to add a comment with: _I have read and agree to the CLA_.

**Comment by guillaumeduhamel** [comment]
I have read and agree to the CLA

**Comment by guillaumeduhamel** [comment]
> @guillaumeduhamel we just need you to add a comment with: _I have read and agree to the CLA_.

@mweichert, ok no problem, is it correct with the comment above ?

**Comment by russellmorton** [comment]
> > @guillaumeduhamel we just need you to add a comment with: _I have read and agree to the CLA_.
> 
> @mweichert, ok no problem, is it correct with the comment above ?

Hi @guillaumeduhamel, that's perfect, thank you!

**Pull request merged**
