### PR TITLE
WIP: add design style

### PR DESCRIPTION
**Pull request by HamidGoudarzi1988**

### CODE REVIEW

**Review by hu3man — CHANGES_REQUESTED** [review]
The design of the elements looks good!

I tried making some variations of tables and found that the alignment and column spacing break in a few cases. I have pushed a commit that includes some additional cases of tables  that we need to handle

**Comment by hu3man** [comment]
The most recent updates on the branch have fixed several things, it looks like it's just the column sizing that's still an issue

There are 2 things I notice:
- The size of columns 2+ are fixed and look bad when col 1 is a short string and col 2+ have longer content
- Only the first col resizes and things look strange at larger window sizes

markdown_table_example

What dynamic or static sizing options are available for this?

**Comment by HamidGoudarzi1988** [comment]
> 



> The most recent updates on the branch have fixed several things, it looks like it's just the column sizing that's still an issue
> 
> There are 2 things I notice:
> 
> * The size of columns 2+ are fixed and look bad when col 1 is a short string and col 2+ have longer content
> * Only the first col resizes and things look strange at larger window sizes
> 
> markdown_table_example
> 
> What dynamic or static sizing options are available for this?

Hi, thanks,  I used "table-layout: auto;" and but it did not fixed the issue and then I tried width:100% for both 'thead' and 'tbody', it filled the width but not equally or the way that we want, please let me know if you have any suggestion that I can test here and fix the issue? thanks

**Comment by hu3man** [comment]
Hey @HamidGoudarzi1988, I'm not sure what the best approach here is 

Were you able to make any progress?

**Comment by HamidGoudarzi1988** [comment]
Hi @hu3man, we've got a fix to the table layout to review, please let me know if it needs more tweaks, thanks

**Comment by hu3man** [comment]
Awesome, thanks @HamidGoudarzi1988. This looks like a good to me!

**Review by hu3man — APPROVED** [review]

**Comment by hu3man** [comment]
@HamidGoudarzi1988 , I seem to have totally messed up this branch with a bad merge. Could you please publish your local changes to a new branch?

Thanks!

**Comment by HamidGoudarzi1988** [comment]
ok sure, this is new pr: https://github.com/ecadlabs/taqueria/pull/317 ,
please let me know if something is missing

**Pull request closed without merging**
