### PR TITLE
Remove default from Zod schema for env field

### LINKED ISSUE #1223: 🐛 Bug ➾ env is set to 'development' in parsed config object implicitly
### 🆘 What happened?

Add `console.error(parsedArgs)` 2 lines below `export const originate = <T>(parsedArgs: Opts) => {` then run `taq deploy <filename>` and you will see this (note `  env: 'development',` below):

```javascript
{
  _: [],
  projectDir: '/Users/jimmychenchen/Desktop/dapp',
  maxConcurrency: 10,
  debug: true,
  disableState: false,
  logPluginRequests: true,
  fromVsCode: true,
  version: false,
  build: false,
  help: false,
  yes: true,
  env: 'development',
  setBuild: '48b0cda5',
  setVersion: 'dev-1200-taq-api-for-dapp-JCC',
  taqRun: 'proxy',
  config: {
    language: 'en',
    contractsDir: 'contracts',
    artifactsDir: 'artifacts',
    network: { ghostnet: [Object] },
    sandbox: { local: [Object] },
    environment: { default: 'testing', development: [Object], testing: [Object] },
    accounts: {
      bob: '3_000_000_000',
      alice: '3_000_000_000',
      john: '3_000_000_000',
      jane: '3_000_000_000',
      joe: '3_000_000_000'
    },
    plugins: [ [Object], [Object], [Object], [Object] ],
    projectDir: '/Users/jimmychenchen/Desktop/dapp',
    configFile: '/Users/jimmychenchen/Desktop/dapp/.taq/config.json',
    hash: '14cf3fe4e96f9cded87f45db91ad554aa81084a1addd2671842909636d5ebd38'
  },
  task: 'deploy',
  i18n: '{}',
  envVars: '{}',
  lock: './deno-lock.json',
  d: 'false',
  p: './',
  y: 'false',
  contract: 'hello-tacos.tz',
  '$0': 'node_modules/@taqueria/plugin-taquito/index.js'
}
```

### 🪵 Relevant log output

_No response_

### 🐘 How impactful is this bug?

_No response_

### ⏱️ Prevalance

_No response_

### 💻 Operating System

_No response_

### 🕸️ System Architecture

_No response_

### 🌮 Taqueria Version

_No response_

### 🌿 Node.js Version

_No response_

### ☎️ Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jchenche**
# 🌮 Taqueria PR

Fixes #1223

## 🪁 Description

A Zod schema had given a default to env so that if we don't specify `--env` in the CLI, it is always set to 'development', never honouring the default environment set in the config file.

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

_Please include a summary of the changes to the codebase._ _Please also include relevant motivation and context for the change_
_(e.g. what was the existing behaviour, why did it break, etc.)_

## 🎢 Test Plan

_Please describe the testing strategy and plan for this PR. Keep this lightweight and anticipate any testing challenges_

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [x] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

### CODE REVIEW

**Review by mweichert — CHANGES_REQUESTED** [review]
Hey @jchenche 

I believe that the core issue we're trying to solve here is this:

End-developers need to be able to target any given environment when invoking a task.

However, I also think that being able to specify a default environment in the config is desirable as well, and this PR doesn't address that.

When I was looking into this, I had concluded that we need a type representation that consolidates arguments given via the CLI and the configuration file. We then don't have to send `ParsedArgs` and `LoadedConfig` as separate parameters to so many of our functions, and instead just pass `ParsedArgs`. Let me explain...

We already have a `ParsedArgs` type, and I think that's an appropriate name for the consolidation I just described. However, currently`ParsedArgs` represents the arguments parsed from the user invoking the CLI. Therefore, I'd probably have a new type called `TaskArgs` or `CLIArgs` to represent the arguments coming from the user via the CLI. We already have LoadedConfig which represents the data coming from the configuration file. We can then refactor `ParsedArgs` to represent the consolidation of those two. I would probably model it as:
```
interface ParsedArgs extends CLIArgs {
  config: LoadedConfig
}
```

In our factory methods for `ParsedArgs`, such as `create()`, we'd then set `env` to config.environments.default if no `env` has been given explicitly. We'd then just need to make sure that all of our functions are using `parsedArgs.env` instead of checking config.environments (which I don't think many functions are doing anyhow).

This approach solves a few problems:
1) We know that `parsedArgs.env` is our source of truth when needing to check what environment to target
2) Our function signatures will be smaller, as we don't need to accept individual parameters for ParsedArgs and LoadedConfig
3) We fix the ability for end-developers to specify what environment they would like to target, and retain the ability for those end-developers to set a default environment, and have that honoured as well.

**Comment by jchenche** [comment]
> 

Referring to this: `However, I also think that being able to specify a default environment in the config is desirable as well, and this PR doesn't address that.`

@mweichert That is what the issue is and what this PR solves.

**Review by mweichert — APPROVED** [review]
@jchenche do you mind creating an issue to add any missing tests for this please? Other than that, solution looks great.

**Review by hu3man — APPROVED** [review]
Wow, what a simple fix for a glaring issue. Looks great. Thanks @jchenche!

**Comment by hu3man** [comment]
Let's merge this in!

**Pull request merged**
