### PR TITLE
correct the wether typo in quickstart.mdx

### PR DESCRIPTION
**Pull request by michaelkernaghan**
PR to close issue #782 

There was a typo on the quickstart.mdx page in the Taqueria docs.

### CODE REVIEW

**Review by russellmorton — APPROVED** [review]

**Comment by michaelkernaghan** [comment]
recheck

**Comment by michaelkernaghan** [comment]
recheck

**Comment by michaelkernaghan** [comment]
recheck

**Review by alexzbusko — APPROVED** [review]

**Review by hu3man — APPROVED** [review]
Thanks @michaelkernaghan!

**Pull request merged**
