### PR TITLE
added sdets as codeowners for tests directory

### PR DESCRIPTION
**Pull request by alexzbusko**

### CODE REVIEW

**Comment by GImbrailo** [comment]
LGTM :rocket:

**Comment by GImbrailo** [comment]
@alexzbusko the CF build failed because of some configuration that I forgot on the preview builds last night. Sorry about this

**Review by sinapsist — APPROVED** [review]
Great idea!

**Comment by hu3man** [comment]
I pushed a commit that fixes the CF build. This is g2g

@mweichert @jevonearth, please review and approve when you can

**Review by hu3man — APPROVED** [review]
G2G

**Pull request merged**
