### PR TITLE
384 contract types generation tests

### PR DESCRIPTION
**Pull request by alexzbusko**
Added tests for operations for the contract types plugin

### CODE REVIEW

**Review by GImbrailo — APPROVED** [review]
The workflow change LGTM

**Review by sinapsist — APPROVED** [review]
The PR LGTM

**Review by hu3man — COMMENTED** [review]
These tests lgtm 

Question: 
Looking at the unit tests for the plugin, I see in `generator.spec.ts`, that only example contracts 1-4 are included, and there are 10 in the `/taqueria-plugin-contract-types/example/contracts` directory

I remember Rick saying those were all for test purposes and I'm not sure if 5-10 were left out intentionally, or if they should be added to maximize coverage

**Comment by hu3man** [comment]
Actually, there's 11 example contracts now. Looks like he added one for the case with the complex pair Claude found

**Comment by hu3man** [comment]
> These tests lgtm
> 
> Question: Looking at the unit tests for the plugin, I see in `generator.spec.ts`, that only example contracts 1-4 are included, and there are 10 in the `/taqueria-plugin-contract-types/example/contracts` directory
> 
> I remember Rick saying those were all for test purposes (and something we will need to maintain after protocol changes) and I'm not sure if 5-10 were left out intentionally, or if they should be added to maximize coverage

@ricklove,  can you provide any information?

**Review by hu3man — APPROVED** [review]

**Pull request merged**
