### PR TITLE
Fixes #714, M1 architecture detection

### LINKED ISSUE #714: [Bug] - M1 Detection reliable

### PR DESCRIPTION
**Pull request by mweichert**
Closes #714

### CODE REVIEW

**Comment by hu3man** [comment]
I'm testing out the branch and I can't get the sandbox started. I tried using the locally built flextesa plugin as well as the npm (`@taqueria/plugin-flextesa`)

I did a `docker system prune` first to clear out any existing images, then initialized a new project using the freshly built taq ( `dev-main`)

Output on my terminal is:
```
❯ taq start sandbox local --logPluginRequests
*** START Call to @taqueria/plugin-flextesa ***
node \
/Users/houstonkrohman/code/taqueria/test/node_modules/@taqueria/plugin-flextesa/index.js \
--taqRun \
pluginInfo \
--i18n \
'{}' \
--config \
'{"language":"en","plugins":[{"name":"@taqueria/plugin-flextesa","type":"npm"}],"contractsDir":"contracts","testsDir":"tests","artifactsDir":"artifacts","environment":{"default":"development","development":{"networks":[],"sandboxes":["local"],"storage":{}}},"sandbox":{"local":{"accounts":{"default":"bob","bob":{"initialBalance":"3000000000"},"alice":{"initialBalance":"2000000000"},"john":{"initialBalance":"4000000000"},"jane":{"initialBalance":"5000000000"},"joe":{"initialBalance":"1000000000"}},"label":"Local Tezos Sandbox","protocol":"PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx","rpcUrl":"http://localhost:20000"}},"network":{},"configFile":{"value":"/Users/houstonkrohman/code/taqueria/test/.taq/config.json"},"configDir":{"value":"./.taq"},"projectDir":{"value":"/Users/houstonkrohman/code/taqueria/test"},"hash":{"value":"71d2e3af13c2e241c3e2a88c15d1c63fc1a18b65e14ad385a3c59aa0c890ffdb"}}' \
--envVars \
'{}' \
--configDir \
'./.taq' \
--projectDir \
'/Users/houstonkrohman/code/taqueria/test' \
--maxConcurrency \
10 \
--debug \
false \
--logPluginRequests \
true \
--fromVsCode \
false \
--setBuild \
'f20ca3c' \
--setVersion \
'dev-main' \
--help \
false
*** END of call to @taqueria/plugin-flextesa ***
*** START Call to @taqueria/plugin-flextesa ***
node \
/Users/houstonkrohman/code/taqueria/test/node_modules/@taqueria/plugin-flextesa/index.js \
--taqRun \
proxy \
--i18n \
'{}' \
--config \
'{"language":"en","plugins":[{"name":"@taqueria/plugin-flextesa","type":"npm"}],"contractsDir":"contracts","testsDir":"tests","artifactsDir":"artifacts","environment":{"default":"development","development":{"networks":[],"sandboxes":["local"],"storage":{}}},"sandbox":{"local":{"accounts":{"default":"bob","bob":{"initialBalance":"3000000000"},"alice":{"initialBalance":"2000000000"},"john":{"initialBalance":"4000000000"},"jane":{"initialBalance":"5000000000"},"joe":{"initialBalance":"1000000000"}},"label":"Local Tezos Sandbox","protocol":"PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx","rpcUrl":"http://localhost:20000"}},"network":{},"configFile":{"value":"/Users/houstonkrohman/code/taqueria/test/.taq/config.json"},"configDir":{"value":"./.taq"},"projectDir":{"value":"/Users/houstonkrohman/code/taqueria/test"},"hash":{"value":"71d2e3af13c2e241c3e2a88c15d1c63fc1a18b65e14ad385a3c59aa0c890ffdb"}}' \
--envVars \
'{}' \
--configDir \
'./.taq' \
--projectDir \
'./' \
--maxConcurrency \
10 \
--debug \
false \
--logPluginRequests \
true \
--fromVsCode \
false \
--setBuild \
'f20ca3c' \
--setVersion \
'dev-main' \
--help \
false \
--d \
false \
--p \
'./' \
--sandboxName \
'local' \
--sandbox \
'sandbox' \
--task \
'start sandbox'
*** END of call to @taqueria/plugin-flextesa ***
Error: Command failed: sh -c "docker run --name local --rm --detach --platform linux/arm64/v8 -p 20000:20000 -p 19229:9229 -v /Users/houstonkrohman/code/taqueria/test:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-main-f20ca3c node index.js --sandbox local"
Unable to find image 'ghcr.io/ecadlabs/taqueria-flextesa:dev-main-f20ca3c' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.

    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:520:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 125,
  signal: null,
  cmd: 'sh -c "docker run --name local --rm --detach --platform linux/arm64/v8 -p 20000:20000 -p 19229:9229 -v /Users/houstonkrohman/code/taqueria/test:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-main-f20ca3c node index.js --sandbox local"'
}
```

**Review by hu3man — APPROVED** [review]
Built and tested this out locally and it works great!

Thanks for getting this pushed out so quick 🏎

**Comment by hu3man** [comment]
@mweichert , should we add Jakartanet to the protocol selector? https://github.com/ecadlabs/taqueria/blob/f20ca3c17a815f1a79722f3fdcbcf2bb67bd212e/taqueria-flextesa-manager/index.ts#L209

```
const getSandboxProtocol = (sandboxName: string, config: Config) => {
    const lens = L.compose(
        'sandbox',
        sandboxName,
        'protocol'
    )
    
    // TODO - This shouldn't be here.
    // A plugin should provide a list of protocols to Taqueria, and
    // Taqueria should make that list known to any plugins that require
    // the list.
    switch (L.get(lens, config)) {
        case 'PsiThaCaT47Zboaw71QWScM8sXeMM7bbQFncK9FLqYc6EKdpjVP':
            return 'Ithaca'
        case 'PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx':
            return 'Hangzhou'
        case 'PtGRANADsDU8R9daYKAgWnQYAJ64omN1o3KMGVCykShA97vQbvV':
            return 'Granada'
        default:
            return 'Alpha'
    }
}
```

**Review by russellmorton — APPROVED** [review]
LGTM

**Pull request merged**
